name: CI-CD

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:

  frontend:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Update Code
        run: cp -r ./* /home/urbanaut/frontend/

      - name: Install Dependencies
        run: npm install
        working-directory: /home/urbanaut/frontend/

      - name: Build
        run: npm run build
        working-directory: /home/urbanaut/frontend/

      - name: Restart PM2
        run: sudo /usr/local/bin/pm2 restart frontend